name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r [requirements_test.txt](http://_vscodecontentref_/3)
          pip install freezegun icmplib==3.0 dnspython==2.8.0

      - name: Run tests
        run: pytest tests -q